### ISSUE TITLE
Uso CFDI / Régimen fiscal

### ISSUE THREAD

**Issue by jparadaa** [AndresRamos/ARSoftware.Contpaqi.Comercial.Api.Community#6]
En mi caso estoy probando crear un documento tipo pedido y el API solicita de manera obligatoria uso CFDI / Régimen fiscal, si no los incluyes en el request, el response es un mensaje de error que estos datos son obligatorios.

Saludos,
Javier

**Comment by AndresRamos** [comment]
Esto paso por que esos datos no podian ser `null` por lo que tenias que asignar un valor correcto.

A partir del release [Development v1.0.2](https://github.com/AndresRamos/ARSoftware.Contpaqi.Comercial.Api.Community/releases/tag/1.0.2-development) hice los datos opcionales.

Ahora puedes dejarlos con el valor `null`
```json
"cliente": {
    "tipo": "ClienteProveedor",
    "codigo": "CTE001",
    "razonSocial": "Cliente 1",
    "rfc": "XAXX010101000",
    "usoCfdi": null,
    "regimenFiscal": null
}
```

O simplemente ya no incluirlos en tu solicitud.
```json
"cliente": {
    "codigo": "CTE001"
}
```
